package beetrap.btfmc.agent.remote;

import beetrap.btfmc.Beetrapfabricmc;
import beetrap.btfmc.agent.AgentCommand;
import beetrap.btfmc.agent.event.AgentTickEventMessage;
import beetrap.btfmc.agent.event.EventMessage;
import beetrap.btfmc.agent.physical.PhysicalAgent;
import beetrap.btfmc.agent.remote.RemoteAgentClient.RemoteAgentHttpException;
import beetrap.btfmc.agent.remote.RemoteAgentClient.RemoteAgentSession;
import beetrap.btfmc.state.BeetrapStateManager;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Queue;
import java.util.concurrent.CompletableFuture;
import net.minecraft.entity.passive.BeeEntity;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.math.Vec3d;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Physical Bip agent whose decisions are generated by BeeCuriousService.
 */
public class RemotePhysicalAgent extends PhysicalAgent {
    private static final Logger LOG = LogManager.getLogger(RemotePhysicalAgent.class);
    private static final String SERVICE_URL_KEY = "BEECURIOUS_SERVICE_URL";
    private static final String DEFAULT_SERVICE_URL = "http://127.0.0.1:8765";
    private static final int HEARTBEAT_INTERVAL_TICKS = 20;
    private static final double PLAYER_BUMP_DISTANCE = 1.0;

    private final RemoteAgentClient remoteAgentClient;
    private final Object connectionLock;
    private final Object eventLock;
    private final Queue<PendingEvent> pendingEvents;
    private CompletableFuture<Void> eventChain;
    private String agentSessionId;
    private Vec3d lastBeeNestPosition;
    private int heartbeatTicks;
    private boolean beeNestMoving;
    private boolean touchingPlayer;
    private boolean connectionFailed;
    private boolean connecting;
    private boolean closed;

    /**
     * Spawns Bip and begins an asynchronous BeeCuriousService session.
     */
    public RemotePhysicalAgent(ServerWorld world, BeetrapStateManager beetrapStateManager) {
        super(world, beetrapStateManager);
        this.remoteAgentClient = new RemoteAgentClient(getServiceUrl());
        this.connectionLock = new Object();
        this.eventLock = new Object();
        this.pendingEvents = new ArrayDeque<>();
        this.eventChain = CompletableFuture.completedFuture(null);
        this.heartbeatTicks = 0;
        this.startSessionConnection();
    }

    @Override
    protected void tickCustom() {
        this.detectPlayerBump();
        this.detectBeeNestMovement();

        synchronized(this.connectionLock) {
            if(this.closed || this.agentSessionId == null) {
                this.heartbeatTicks = 0;
                return;
            }
        }

        synchronized(this.eventLock) {
            if(!this.eventChain.isDone()) {
                return;
            }
        }

        this.heartbeatTicks++;
        if(this.heartbeatTicks >= HEARTBEAT_INTERVAL_TICKS) {
            this.heartbeatTicks = 0;
            this.sendHeartbeat();
        }
    }

    @Override
    public void sendGptEventMessage(EventMessage eventMessage) {
        PendingEvent pendingEvent = new PendingEvent(eventMessage.toJsonString(),
                this.instructionBuilder.contextInstructionBuilder().toString(),
                List.of(), List.of(), List.of());
        String activeSessionId;

        synchronized(this.connectionLock) {
            if(this.closed) {
                return;
            }
            activeSessionId = this.agentSessionId;
            if(activeSessionId == null) {
                this.pendingEvents.add(pendingEvent);
            }
        }

        if(activeSessionId == null) {
            this.startSessionConnection();
        } else {
            this.sendEvent(activeSessionId, pendingEvent);
        }
    }

    private void sendEvent(String activeSessionId, PendingEvent event) {
        synchronized(this.eventLock) {
            this.eventChain = this.eventChain
                    .thenCompose(unused -> this.remoteAgentClient.sendEvent(activeSessionId,
                            event.eventJson(), event.context()))
                    .thenAccept(commands -> {
                        for(AgentCommand command : commands) {
                            if(this.addCommand(command)) {
                                LOG.info("Queueing remote agent command: {}", command);
                            } else {
                                LOG.debug("Ignoring duplicate remote command {}",
                                        command.commandId());
                            }
                        }
                        this.acknowledgeCommandStatuses(
                                event.completedCommandIds(),
                                event.failedCommandIds()
                        );
                    })
                    .exceptionally(throwable -> {
                        if(this.isSessionNotFound(throwable)) {
                            LOG.warn("BeeCuriousService session expired; creating a new session");
                            this.reconnectAfterExpiredSession(activeSessionId, event);
                        } else {
                            LOG.error("BeeCuriousService failed to handle agent event", throwable);
                            this.getBeetrapStateManager().requeueAgentEvents(
                                    event.agentEvents());
                        }
                        return null;
                    });
        }
    }

    private void startSessionConnection() {
        synchronized(this.connectionLock) {
            if(this.closed || this.connecting || this.agentSessionId != null) {
                return;
            }
            this.connecting = true;
            this.connectionFailed = false;
        }
        this.remoteAgentClient.createSession(
                Beetrapfabricmc.SESSION_ID,
                Beetrapfabricmc.PLAYER_DATA_CONSENT,
                Beetrapfabricmc.PARTICIPANT_ID
        ).whenComplete(this::onSessionCreated);
    }

    private void onSessionCreated(RemoteAgentSession newSession, Throwable throwable) {
        Queue<PendingEvent> eventsToSend = new ArrayDeque<>();
        synchronized(this.connectionLock) {
            this.connecting = false;
            if(throwable != null) {
                this.connectionFailed = true;
                LOG.error("Could not create BeeCuriousService agent session", throwable);
                return;
            }
            if(this.closed) {
                this.remoteAgentClient.closeSession(newSession.agentSessionId());
                return;
            }

            this.agentSessionId = newSession.agentSessionId();
            eventsToSend.addAll(this.pendingEvents);
            this.pendingEvents.clear();
        }

        LOG.info("Connected {} profile {} to BeeCuriousService session {}",
                newSession.agentName(), newSession.profileId(), newSession.agentSessionId());
        for(PendingEvent event : eventsToSend) {
            this.sendEvent(newSession.agentSessionId(), event);
        }
    }

    private void reconnectAfterExpiredSession(String expiredSessionId, PendingEvent event) {
        synchronized(this.connectionLock) {
            if(this.closed) {
                return;
            }
            if(expiredSessionId.equals(this.agentSessionId)) {
                this.agentSessionId = null;
                this.heartbeatTicks = 0;
            }
            this.pendingEvents.add(event);
        }
        this.startSessionConnection();
    }

    private boolean isSessionNotFound(Throwable throwable) {
        Throwable current = throwable;
        while(current != null) {
            if(current instanceof RemoteAgentHttpException httpException) {
                return httpException.getStatusCode() == 404;
            }
            current = current.getCause();
        }
        return false;
    }

    @Override
    public void close() {
        String activeSessionId;
        synchronized(this.connectionLock) {
            this.closed = true;
            this.pendingEvents.clear();
            activeSessionId = this.agentSessionId;
            this.heartbeatTicks = 0;
        }
        if(activeSessionId != null) {
            this.remoteAgentClient.closeSession(activeSessionId);
        }
        super.close();
    }

    private static String getServiceUrl() {
        String fromProperty = System.getProperty(SERVICE_URL_KEY);
        if(fromProperty != null && !fromProperty.isBlank()) {
            return fromProperty;
        }

        String fromEnv = System.getenv(SERVICE_URL_KEY);
        if(fromEnv != null && !fromEnv.isBlank()) {
            return fromEnv;
        }

        return DEFAULT_SERVICE_URL;
    }

    private void sendHeartbeat() {
        List<String> completed = this.getCompletedCommandIds();
        List<String> failed = this.getFailedCommandIds();
        List<Map<String, Object>> events =
                this.getBeetrapStateManager().drainAgentEvents();
        EventMessage heartbeat = new AgentTickEventMessage(
                this.buildSnapshot(events),
                this.buildExecutionSnapshot(completed, failed)
        );
        String activeSessionId;
        synchronized(this.connectionLock) {
            activeSessionId = this.agentSessionId;
        }
        if(activeSessionId != null) {
            this.sendEvent(
                    activeSessionId,
                    new PendingEvent(
                            heartbeat.toJsonString(),
                            "",
                            completed,
                            failed,
                            events
                    )
            );
        }
    }

    private Map<String, Object> buildSnapshot(List<Map<String, Object>> events) {
        Map<String, Object> snapshot = new LinkedHashMap<>();
        snapshot.put("game_tick", this.world.getTime());
        snapshot.put("current_diversity",
                this.getBeetrapStateManager().getCurrentDiversityScore());
        snapshot.put("events", events);

        ServerPlayerEntity player = this.world.getPlayers().isEmpty()
                ? null : this.world.getPlayers().getFirst();
        snapshot.put("player", this.entitySnapshot(player == null ? null : player.getPos(),
                player == null ? null : player.getHeadYaw()));

        BeeEntity bee = this.getBeeEntity();
        snapshot.put("agent", this.entitySnapshot(bee.getPos(), bee.getHeadYaw()));
        snapshot.put("flowers", this.buildFlowerSnapshot());
        return snapshot;
    }

    private void detectPlayerBump() {
        if(this.world.getPlayers().isEmpty()) {
            this.touchingPlayer = false;
            return;
        }
        ServerPlayerEntity player = this.world.getPlayers().getFirst();
        Vec3d agentPosition = this.getBeeEntity().getPos();
        double distance = agentPosition.distanceTo(player.getPos());
        boolean touching = this.getBeeEntity().getBoundingBox()
                .expand(PLAYER_BUMP_DISTANCE / 2)
                .intersects(player.getBoundingBox());
        if(touching && !this.touchingPlayer) {
            this.getBeetrapStateManager().recordAgentEvent(
                    "agent_bumped_player",
                    Map.of(
                            "distance", distance,
                            "agent_position", positionList(agentPosition),
                            "player_position", positionList(player.getPos())
                    )
            );
        }
        this.touchingPlayer = touching;
    }

    private void detectBeeNestMovement() {
        Vec3d currentPosition = this.getBeetrapStateManager()
                .getBeeNestController()
                .getBeeNestPosition();
        boolean moving = this.lastBeeNestPosition != null
                && currentPosition.distanceTo(this.lastBeeNestPosition) > 0.01;
        if(moving && !this.beeNestMoving) {
            this.getBeetrapStateManager().recordAgentEvent(
                    "beehive_moving",
                    Map.of(
                            "from", positionList(this.lastBeeNestPosition),
                            "to", positionList(currentPosition),
                            "distance", currentPosition.distanceTo(this.lastBeeNestPosition)
                    )
            );
        }
        this.beeNestMoving = moving;
        this.lastBeeNestPosition = currentPosition;
    }

    private static List<Double> positionList(Vec3d position) {
        return List.of(position.x, position.y, position.z);
    }

    private Map<String, Object> entitySnapshot(Vec3d position, Float headYaw) {
        Map<String, Object> entity = new LinkedHashMap<>();
        if(position == null) {
            entity.put("position", List.of(0.0, 0.0, 0.0));
        } else {
            entity.put("position", List.of(position.x, position.y, position.z));
        }
        if(headYaw != null) {
            entity.put("head_yaw", headYaw);
        }
        return entity;
    }

    private Map<String, Object> buildFlowerSnapshot() {
        List<Map<String, Object>> flowers = new ArrayList<>();
        BeetrapStateManager stateManager = this.getBeetrapStateManager();
        for(beetrap.btfmc.flower.Flower flower : stateManager.getState()) {
            Vec3d position = stateManager.getFlowerManager()
                    .getFlowerMinecraftPosition(stateManager.getState(), flower);
            if(position == null) {
                continue;
            }
            Map<String, Object> item = new LinkedHashMap<>();
            item.put("id", flower.getNumber());
            item.put("position", List.of(position.x, position.y, position.z));
            item.put("color", stateManager.getFlowerManager()
                    .getFlowerMinecraftColor(flower));
            item.put("withered", flower.hasWithered());
            flowers.add(item);
        }
        return Map.of("count", flowers.size(), "items", flowers);
    }

    private Map<String, Object> buildExecutionSnapshot(
            List<String> completed,
            List<String> failed) {
        Map<String, Object> execution = new LinkedHashMap<>();
        execution.put("current_command_id", this.getCurrentCommandId());
        execution.put("queued_command_ids", this.getQueuedCommandIds());
        execution.put("completed_command_ids", completed);
        execution.put("failed_command_ids", failed);
        return execution;
    }

    private record PendingEvent(
            String eventJson,
            String context,
            List<String> completedCommandIds,
            List<String> failedCommandIds,
            List<Map<String, Object>> agentEvents
    ) {
    }
}
