package beetrap.btfmc.agent.remote;

import beetrap.btfmc.Beetrapfabricmc;
import beetrap.btfmc.agent.AgentCommand;
import beetrap.btfmc.agent.event.EventMessage;
import beetrap.btfmc.agent.physical.PhysicalAgent;
import beetrap.btfmc.agent.remote.RemoteAgentClient.RemoteAgentHttpException;
import beetrap.btfmc.agent.remote.RemoteAgentClient.RemoteAgentSession;
import beetrap.btfmc.state.BeetrapStateManager;
import java.util.ArrayDeque;
import java.util.Queue;
import java.util.concurrent.CompletableFuture;
import net.minecraft.server.world.ServerWorld;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Physical Bip agent whose decisions are generated by BeeCuriousService.
 */
public class RemotePhysicalAgent extends PhysicalAgent {
    private static final Logger LOG = LogManager.getLogger(RemotePhysicalAgent.class);
    private static final String SERVICE_URL_KEY = "BEECURIOUS_SERVICE_URL";
    private static final String DEFAULT_SERVICE_URL = "http://127.0.0.1:8765";

    private final RemoteAgentClient remoteAgentClient;
    private final Object connectionLock;
    private final Object eventLock;
    private final Queue<PendingEvent> pendingEvents;
    private CompletableFuture<Void> eventChain;
    private String agentSessionId;
    private boolean connectionFailed;
    private boolean connecting;
    private boolean closed;

    /**
     * Spawns Bip and begins an asynchronous BeeCuriousService session.
     */
    public RemotePhysicalAgent(ServerWorld world, BeetrapStateManager beetrapStateManager) {
        super(world, beetrapStateManager);
        this.remoteAgentClient = new RemoteAgentClient(getServiceUrl());
        this.connectionLock = new Object();
        this.eventLock = new Object();
        this.pendingEvents = new ArrayDeque<>();
        this.eventChain = CompletableFuture.completedFuture(null);
        this.startSessionConnection();
    }

    @Override
    public void sendGptEventMessage(EventMessage eventMessage) {
        PendingEvent pendingEvent = new PendingEvent(eventMessage.toJsonString(),
                this.instructionBuilder.contextInstructionBuilder().toString());
        String activeSessionId;

        synchronized(this.connectionLock) {
            if(this.closed) {
                return;
            }
            activeSessionId = this.agentSessionId;
            if(activeSessionId == null) {
                this.pendingEvents.add(pendingEvent);
            }
        }

        if(activeSessionId == null) {
            this.startSessionConnection();
        } else {
            this.sendEvent(activeSessionId, pendingEvent);
        }
    }

    private void sendEvent(String activeSessionId, PendingEvent event) {
        synchronized(this.eventLock) {
            this.eventChain = this.eventChain
                    .thenCompose(unused -> this.remoteAgentClient.sendEvent(activeSessionId,
                            event.eventJson(), event.context()))
                    .thenAccept(commands -> {
                        for(AgentCommand command : commands) {
                            LOG.info("Queueing remote agent command: {}", command);
                            this.addCommand(command);
                        }
                    })
                    .exceptionally(throwable -> {
                        if(this.isSessionNotFound(throwable)) {
                            LOG.warn("BeeCuriousService session expired; creating a new session");
                            this.reconnectAfterExpiredSession(activeSessionId, event);
                        } else {
                            LOG.error("BeeCuriousService failed to handle agent event", throwable);
                        }
                        return null;
                    });
        }
    }

    private void startSessionConnection() {
        synchronized(this.connectionLock) {
            if(this.closed || this.connecting || this.agentSessionId != null) {
                return;
            }
            this.connecting = true;
            this.connectionFailed = false;
        }
        this.remoteAgentClient.createSession(
                Beetrapfabricmc.SESSION_ID,
                Beetrapfabricmc.PLAYER_DATA_CONSENT,
                Beetrapfabricmc.PARTICIPANT_ID
        ).whenComplete(this::onSessionCreated);
    }

    private void onSessionCreated(RemoteAgentSession newSession, Throwable throwable) {
        Queue<PendingEvent> eventsToSend = new ArrayDeque<>();
        synchronized(this.connectionLock) {
            this.connecting = false;
            if(throwable != null) {
                this.connectionFailed = true;
                LOG.error("Could not create BeeCuriousService agent session", throwable);
                return;
            }
            if(this.closed) {
                this.remoteAgentClient.closeSession(newSession.agentSessionId());
                return;
            }

            this.agentSessionId = newSession.agentSessionId();
            eventsToSend.addAll(this.pendingEvents);
            this.pendingEvents.clear();
        }

        LOG.info("Connected {} profile {} to BeeCuriousService session {}",
                newSession.agentName(), newSession.profileId(), newSession.agentSessionId());
        for(PendingEvent event : eventsToSend) {
            this.sendEvent(newSession.agentSessionId(), event);
        }
    }

    private void reconnectAfterExpiredSession(String expiredSessionId, PendingEvent event) {
        synchronized(this.connectionLock) {
            if(this.closed) {
                return;
            }
            if(expiredSessionId.equals(this.agentSessionId)) {
                this.agentSessionId = null;
            }
            this.pendingEvents.add(event);
        }
        this.startSessionConnection();
    }

    private boolean isSessionNotFound(Throwable throwable) {
        Throwable current = throwable;
        while(current != null) {
            if(current instanceof RemoteAgentHttpException httpException) {
                return httpException.getStatusCode() == 404;
            }
            current = current.getCause();
        }
        return false;
    }

    @Override
    public void close() {
        String activeSessionId;
        synchronized(this.connectionLock) {
            this.closed = true;
            this.pendingEvents.clear();
            activeSessionId = this.agentSessionId;
        }
        if(activeSessionId != null) {
            this.remoteAgentClient.closeSession(activeSessionId);
        }
        super.close();
    }

    private static String getServiceUrl() {
        String fromProperty = System.getProperty(SERVICE_URL_KEY);
        if(fromProperty != null && !fromProperty.isBlank()) {
            return fromProperty;
        }

        String fromEnv = System.getenv(SERVICE_URL_KEY);
        if(fromEnv != null && !fromEnv.isBlank()) {
            return fromEnv;
        }

        return DEFAULT_SERVICE_URL;
    }

    private record PendingEvent(String eventJson, String context) {
    }
}
